### ISSUE TITLE
Размер шрифта

### ISSUE THREAD

**Issue by emilg1101** [Jaskelai/charts#5]
Добавьте возможность изменения размера шрифта для лейблов.

**Comment by emilg1101** [comment]
![image](https://user-images.githubusercontent.com/15985979/66406886-07e1ab00-e9f5-11e9-8a7d-c8d5f5803051.png)

**Comment by Jaskelai** [comment]
Посмотрим

**Comment by Jaskelai** [comment]
Найс ноуты в фиксе выдают

**Comment by emilg1101** [comment]
Хорошо 
Ждем

**Comment by Jaskelai** [comment]
Добавил возможность смены размера текста
